// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdpxlzebueprmbzifitk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcHhsemVidWVwcm1iemlmaXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Nzc5MzMsImV4cCI6MjA2NTA1MzkzM30.sK-7oSqc7D1jpGAqL-gEKrUOyBqmfAElcXC6g8ODd6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);